#ifndef CONFIG_HPP
#define CONFIG_HPP
#define NUMBER_OF_THRUSTERS 7
#define INIT_THRUSTER_PWM 1474
#define THRUSTER_PINS {2, 3, 4, 5, 6, 7, 8}
#define THRUSTER_MIN_PWM 1000
#define THRUSTER_MAX_PWM 2000
#define NORMAL_MODE 0
#define CALIBRATION_MODE 1
#define CALIBRATION_UPDATE_MODE 2
#define G 9.80665
#endif // CONFIG_HPP